from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app import mock_data
from app.aivana import AivanaError
from app.config import settings
from app.db import get_db
from app.fit_analysis import analyze_fit
from app.models import SearchLog
from app.schemas import FitAnalysisRequest, FitAnalysisResult, Job, JobSearchRequest

router = APIRouter(prefix="/api/jobs", tags=["jobs"])


@router.post("/search", response_model=list[Job])
def search_jobs(req: JobSearchRequest, db: Session = Depends(get_db)) -> list[Job]:
    """Mocked job search. Filters the placeholder list so the UI has something to react to."""
    needle = req.role.lower()
    results = [j for j in mock_data.JOBS if needle in j.title.lower()] or mock_data.JOBS

    db.add(
        SearchLog(
            role=req.role,
            location=req.location,
            remote=req.remote,
            result_count=len(results),
        )
    )
    db.commit()
    return results


@router.post("/fit-analysis", response_model=FitAnalysisResult)
def fit_analysis(req: FitAnalysisRequest) -> FitAnalysisResult:
    """Generated by Aivana MMI when AIVANA_MODE=live, canned otherwise."""
    if settings.aivana_mode == "mock":
        return mock_data.FIT_ANALYSIS
    try:
        return analyze_fit(req)
    except AivanaError as e:
        raise HTTPException(
            status_code=502,
            detail={"message": str(e), "code": e.code, "request_id": e.request_id},
        ) from e
