"""Fit analysis generated by Aivana MMI.

The JSON template goes in the prompt itself: in testing, Aivana ignored format
instructions given only in `system` and invented its own keys.
"""

import json

from pydantic import ValidationError

from app import aivana
from app.schemas import FitAnalysisRequest, FitAnalysisResult

TEMPLATE = '{"summary": "<1-2 sentences>", "strengths": ["..."], "gaps": ["..."], "recommendations": ["..."]}'

# AI output is probabilistic, so a wrong shape gets one more try before we give up.
ATTEMPTS = 2


def build_prompt(req: FitAnalysisRequest) -> str:
    data = {
        "job": req.job.model_dump(exclude={"id", "url"}),
        "candidate": req.user_profile.model_dump(),
    }
    return (
        "Assess how well the candidate fits the job. Be specific to this job and this candidate.\n\n"
        f"INPUT:\n{json.dumps(data)}\n\n"
        "Return ONLY a JSON object that matches this exact template "
        "(same keys, no extra keys, 2-4 items per list):\n"
        f"{TEMPLATE}"
    )


def analyze_fit(req: FitAnalysisRequest) -> FitAnalysisResult:
    prompt = build_prompt(req)
    request_id = None
    for _ in range(ATTEMPTS):
        res = aivana.generate(prompt, output_shape="extract")
        request_id = res.get("request_id")
        try:
            return FitAnalysisResult.model_validate(res.get("structured"))
        except ValidationError:
            continue
    raise aivana.AivanaError(
        "Aivana's answer did not match the fit analysis format",
        code="bad_output",
        request_id=request_id,
    )
